local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "reviews"
    label: "Reviews"
    label_singular: "Review"
    folder: "src/reviews"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Game title", name: "title", widget: "string" }
      - label: "Genre"
        name: "meta"
        widget: "select"
        multiple: true
        options: ["Action", "RPG", "Soulslike", "Open-World", "Racing", "Adventure", "Shooter", "Strategy", "Simulation",
          "Sports", "Puzzle", "Horror", "Platformer", "Fighting", "MMO", "Stealth", "Survival", "Rhythm", "Visual Novel", "Party", "Educational"]
      - { label: "Cover image", name: "cover_image", widget: "image", required: false }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Short excerpt (shown on cards)", name: "excerpt", widget: "text" }
      - { label: "Review body (hook + story)", name: "body", widget: "markdown" }
      - { label: "Pros", name: "pros", widget: "list" }
      - { label: "Cons", name: "cons", widget: "list" }
      - { label: "Rating", name: "cta", widget: "string", required: true }
      
  - name: "news"
    label: "News"
    label_singular: "News item"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Short excerpt (shown on cards)", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Short excerpt (shown on cards)", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }